# Deployment, Service, HPA 통합 (post-service / ALB)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  labels:
    app: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: 245040175511.dkr.ecr.ap-northeast-2.amazonaws.com/post-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: post-db-secret
            - secretRef:
                name: post-secrets
          env:
            - name: S3_BUCKET_NAME
              value: "karina-winter"
            - name: S3_REGION
              value: "ap-northeast-2"
            - name: S3_FOLDER_PREFIX
              value: "image_files"
            - name: CLOUDFRONT_DOMAIN
              value: "d1yro8photnpwi.cloudfront.net"
            - name: API_GATEWAY_DOMAIN
              value: "api.hhottdogg.shop"
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "700m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: post-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: post-service-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
